// Apne aas-paas ke schools yahan add karte jao.
// Jo list me nahi hai wo user khud type kar sakta hai.
export const SCHOOL_OPTIONS = [
  "Kendriya Vidyalaya",
  "Jawahar Navodaya Vidyalaya",
  "Saraswati Shishu Mandir",
  "Government Inter College",
  "Government High School",
  "St. Joseph's College",
  "St. Mary's Convent School",
  "St. Xavier's School",
  "St. Anthony's School",
  "Delhi Public School",
  "DAV Public School",
  "Army Public School",
  "Kendriya Vidyalaya New Cantt",
  "Boys High School & College",
  "Girls High School & College",
  "Bishop Johnson School",
  "Mary Lucas School",
  "Maharishi Patanjali Vidya Mandir",
  "Sunbeam School",
  "City Montessori School",
  "Little Flower School",
  "Holy Cross School",
  "Bethany Convent School",
  "Jagat Taran Golden Jubilee School",
  "SMC Model School",
  "MV Convent Inter College",
  "St. Paul's School",
  "St. Peter's School",
  "Other",
];