import { Router, type IRouter } from "express";
import institutesRouter from "./institutes";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import studentsRouter from "./students";
import staffRouter from "./staff";
import coursesRouter from "./courses";
import subjectsRouter from "./subjects";
import batchesRouter from "./batches";
import timetableRouter from "./timetable";
import attendanceRouter from "./attendance";
import homeworkRouter from "./homework";
import homeworkSubmissionsRouter from "./homework-submissions";
import testsRouter from "./test";
import financeRouter from "./finance";
import hrRouter from "./hr";
import analyticsRouter from "./analytics";
import notificationsRouter from "./notifications";
import admissionsRouter from "./admissions";
import ptmRouter from "./ptm";

const router: IRouter = Router();

router.use(institutesRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(studentsRouter);
router.use(staffRouter);
router.use(coursesRouter);
router.use(subjectsRouter);
router.use(batchesRouter);
router.use(timetableRouter);
router.use(attendanceRouter);
router.use(homeworkRouter);
router.use(homeworkSubmissionsRouter);
router.use(testsRouter);
router.use(financeRouter);
router.use(hrRouter);
router.use(analyticsRouter);
router.use(notificationsRouter);
router.use(admissionsRouter);
router.use(ptmRouter);

export default router;
